package com.blitzagency.utils.form
{
	
	public class CountriesArray extends Object
	{	
		public static function get CountriesG7():Array
		{
			var a : Array = new Array();
			a.push({label:"Canada", id:"Canada"});
			a.push({label:"France", id:"France"});
			a.push({label:"Germany", id:"Germany"});
			a.push({label:"Italy", id:"Italy"});
			a.push({label:"Japan", id:"Japan"});
			a.push({label:"United Kingdom", id:"United Kingdom"});
			a.push({label:"United States", id:"United States"});
			return a;
		}
		
		public static function get CountriesAll():Array
		{
			var a : Array = new Array();
			a.push({label:"Afghanistan", id:"Afghanistan"});
			a.push({label:"Albania", id:"Albania"});
			a.push({label:"Algeria", id:"Algeria"});
			a.push({label:"American Samoa", id:"American Samoa"});
			a.push({label:"Andorra", id:"Andorra"});
			a.push({label:"Angola", id:"Angola"});
			a.push({label:"Anguilla", id:"Anguilla"});
			a.push({label:"Antigua and Barbuda", id:"Antigua and Barbuda"});
			a.push({label:"Argentina", id:"Argentina"});
			a.push({label:"Armenia", id:"Armenia"});
			a.push({label:"Aruba", id:"Aruba"});
			a.push({label:"Australia", id:"Australia"});
			a.push({label:"Austria", id:"Austria"});
			a.push({label:"Azerbaijan", id:"Azerbaijan"});
			a.push({label:"Bahamas", id:"Bahamas"});
			a.push({label:"Bangladesh", id:"Bangladesh"});
			a.push({label:"Barbados", id:"Barbados"});
			a.push({label:"Belarus", id:"Belarus"});
			a.push({label:"Belgium", id:"Belgium"});
			a.push({label:"Belize", id:"Belize"});
			a.push({label:"Benin", id:"Benin"});
			a.push({label:"Bermuda", id:"Bermuda"});
			a.push({label:"Bhutan", id:"Bhutan"});
			a.push({label:"Bolivia", id:"Bolivia"});
			a.push({label:"Bosnia and Herzegovina", id:"Bosnia and Herzegovina"});
			a.push({label:"Botswana", id:"Botswana"});
			a.push({label:"Bouvet Island", id:"Bouvet Island"});
			a.push({label:"Brazil", id:"Brazil"});
			a.push({label:"British Indian Ocean Territory", id:"British Indian Ocean Territory"});
			a.push({label:"Brunei Darussalam", id:"Brunei Darussalam"});
			a.push({label:"Bulgaria", id:"Bulgaria"});
			a.push({label:"Burkina Faso", id:"Burkina Faso"});
			a.push({label:"Burundi", id:"Burundi"});
			a.push({label:"Cambodia", id:"Cambodia"});
			a.push({label:"Cameroon", id:"Cameroon"});
			a.push({label:"Canada", id:"Canada"});
			a.push({label:"Cape Verde", id:"Cape Verde"});
			a.push({label:"Cayman Islands", id:"Cayman Islands"});
			a.push({label:"Central African Republic", id:"Central African Republic"});
			a.push({label:"Chad", id:"Chad"});
			a.push({label:"Chile", id:"Chile"});
			a.push({label:"China", id:"China"});
			a.push({label:"Christmas Island", id:"Christmas Island"});
			a.push({label:"Cocos (Keeling) Islands", id:"Cocos (Keeling) Islands"});
			a.push({label:"Colombia", id:"Colombia"});
			a.push({label:"Comoros", id:"Comoros"});
			a.push({label:"Congo", id:"Congo"});
			a.push({label:"Congo, Democratic Republic of the", id:"Congo, Democratic Republic of the"});
			a.push({label:"Cook Islands", id:"Cook Islands"});
			a.push({label:"Costa Rica", id:"Costa Rica"});
			a.push({label:"Croatia", id:"Croatia"});
			a.push({label:"Cuba", id:"Cuba"});
			a.push({label:"Cyprus", id:"Cyprus"});
			a.push({label:"Czech Republic", id:"Czech Republic"});
			a.push({label:"Côte d'Ivoire", id:"Côte d'Ivoire"});
			a.push({label:"Denmark", id:"Denmark"});
			a.push({label:"Djibouti", id:"Djibouti"});
			a.push({label:"Dominica", id:"Dominica"});
			a.push({label:"Dominican Republic", id:"Dominican Republic"});
			a.push({label:"Ecuador", id:"Ecuador"});
			a.push({label:"Egypt", id:"Egypt"});
			a.push({label:"El Salvador", id:"El Salvador"});
			a.push({label:"Equatorial Guinea", id:"Equatorial Guinea"});
			a.push({label:"Eritrea", id:"Eritrea"});
			a.push({label:"Estonia", id:"Estonia"});
			a.push({label:"Ethiopia", id:"Ethiopia"});
			a.push({label:"Falkland Islands (Malvinas)", id:"Falkland Islands (Malvinas)"});
			a.push({label:"Faroe Islands", id:"Faroe Islands"});
			a.push({label:"Fiji", id:"Fiji"});
			a.push({label:"Finland", id:"Finland"});
			a.push({label:"France", id:"France"});
			a.push({label:"French Guiana", id:"French Guiana"});
			a.push({label:"French Polynesia", id:"French Polynesia"});
			a.push({label:"French Southern Territories", id:"French Southern Territories"});
			a.push({label:"Gabon", id:"Gabon"});
			a.push({label:"Georgia", id:"Georgia"});
			a.push({label:"Germany", id:"Germany"});
			a.push({label:"Ghana", id:"Ghana"});
			a.push({label:"Gibraltar", id:"Gibraltar"});
			a.push({label:"Greece", id:"Greece"});
			a.push({label:"Greenland", id:"Greenland"});
			a.push({label:"Grenada", id:"Grenada"});
			a.push({label:"Guadeloupe", id:"Guadeloupe"});
			a.push({label:"Guam", id:"Guam"});
			a.push({label:"Guatemala", id:"Guatemala"});
			a.push({label:"Guernsey", id:"Guernsey"});
			a.push({label:"Guinea", id:"Guinea"});
			a.push({label:"Guinea-Bissau", id:"Guinea-Bissau"});
			a.push({label:"Guyana", id:"Guyana"});
			a.push({label:"Haiti", id:"Haiti"});
			a.push({label:"Holy See (Vatican City State)", id:"Holy See (Vatican City State)"});
			a.push({label:"Honduras", id:"Honduras"});
			a.push({label:"Hong Kong", id:"Hong Kong"});
			a.push({label:"Hungary", id:"Hungary"});
			a.push({label:"Iceland", id:"Iceland"});
			a.push({label:"India", id:"India"});
			a.push({label:"Indonesia", id:"Indonesia"});
			a.push({label:"Iran, Islamic Republic of", id:"Iran, Islamic Republic of"});
			a.push({label:"Iraq", id:"Iraq"});
			a.push({label:"Ireland", id:"Ireland"});
			a.push({label:"Isle of Man", id:"Isle of Man"});
			a.push({label:"Israel", id:"Israel"});
			a.push({label:"Italy", id:"Italy"});
			a.push({label:"Japan", id:"Japan"});
			a.push({label:"Jersey", id:"Jersey"});
			a.push({label:"Jordan", id:"Jordan"});
			a.push({label:"Kazakhstan", id:"Kazakhstan"});
			a.push({label:"Kenya", id:"Kenya"});
			a.push({label:"Kiribati", id:"Kiribati"});
			a.push({label:"Korea, Democratic People's Republic of", id:"Korea, Democratic People's Republic of"});
			a.push({label:"Korea, Republic of", id:"Korea, Republic of"});
			a.push({label:"Kuwait", id:"Kuwait"});
			a.push({label:"Kyrgyzstan", id:"Kyrgyzstan"});
			a.push({label:"Lao People's Democratic Republic", id:"Lao People's Democratic Republic"});
			a.push({label:"Latvia", id:"Latvia"});
			a.push({label:"Lebanon", id:"Lebanon"});
			a.push({label:"Lesotho", id:"Lesotho"});
			a.push({label:"Liberia", id:"Liberia"});
			a.push({label:"Libyan Arab Jamahiriya", id:"Libyan Arab Jamahiriya"});
			a.push({label:"Liechtenstein", id:"Liechtenstein"});
			a.push({label:"Lithuania", id:"Lithuania"});
			a.push({label:"Luxembourg", id:"Luxembourg"});
			a.push({label:"Macedonia, the former Yugoslav Republic of", id:"Macedonia, the former Yugoslav Republic of"});
			a.push({label:"Madagascar", id:"Madagascar"});
			a.push({label:"Malawi", id:"Malawi"});
			a.push({label:"Malaysia", id:"Malaysia"});
			a.push({label:"Maldives", id:"Maldives"});
			a.push({label:"Mali", id:"Mali"});
			a.push({label:"Malta", id:"Malta"});
			a.push({label:"Marshall Islands", id:"Marshall Islands"});
			a.push({label:"Martinique", id:"Martinique"});
			a.push({label:"Mauritania", id:"Mauritania"});
			a.push({label:"Mauritius", id:"Mauritius"});
			a.push({label:"Mayotte", id:"Mayotte"});
			a.push({label:"Mexico", id:"Mexico"});
			a.push({label:"Micronesia, Federated States of", id:"Micronesia, Federated States of"});
			a.push({label:"Moldova, Republic of", id:"Moldova, Republic of"});
			a.push({label:"Monaco", id:"Monaco"});
			a.push({label:"Mongolia", id:"Mongolia"});
			a.push({label:"Montenegro", id:"Montenegro"});
			a.push({label:"Montserrat", id:"Montserrat"});
			a.push({label:"Morocco", id:"Morocco"});
			a.push({label:"Mozambique", id:"Mozambique"});
			a.push({label:"Myanmar", id:"Myanmar"});
			a.push({label:"Namibia", id:"Namibia"});
			a.push({label:"Nauru", id:"Nauru"});
			a.push({label:"Nepal", id:"Nepal"});
			a.push({label:"Netherlands", id:"Netherlands"});
			a.push({label:"Netherlands Antilles", id:"Netherlands Antilles"});
			a.push({label:"New Caledonia", id:"New Caledonia"});
			a.push({label:"New Zealand", id:"New Zealand"});
			a.push({label:"Nicaragua", id:"Nicaragua"});
			a.push({label:"Niger", id:"Niger"});
			a.push({label:"Nigeria", id:"Nigeria"});
			a.push({label:"Niue", id:"Niue"});
			a.push({label:"Norfolk Island", id:"Norfolk Island"});
			a.push({label:"Northern Mariana Islands", id:"Northern Mariana Islands"});
			a.push({label:"Norway", id:"Norway"});
			a.push({label:"Oman", id:"Oman"});
			a.push({label:"Pakistan", id:"Pakistan"});
			a.push({label:"Palau", id:"Palau"});
			a.push({label:"Palestinian Territory, Occupied", id:"Palestinian Territory, Occupied"});
			a.push({label:"Panama", id:"Panama"});
			a.push({label:"Papua New Guinea", id:"Papua New Guinea"});
			a.push({label:"Paraguay", id:"Paraguay"});
			a.push({label:"Peru", id:"Peru"});
			a.push({label:"Philippines", id:"Philippines"});
			a.push({label:"Pitcairn", id:"Pitcairn"});
			a.push({label:"Poland", id:"Poland"});
			a.push({label:"Portugal", id:"Portugal"});
			a.push({label:"Puerto Rico", id:"Puerto Rico"});
			a.push({label:"Qatar", id:"Qatar"});
			a.push({label:"Romania", id:"Romania"});
			a.push({label:"Russian Federation", id:"Russian Federation"});
			a.push({label:"Rwanda", id:"Rwanda"});
			a.push({label:"Réunion", id:"Réunion"});
			a.push({label:"Saint Barthélemy", id:"Saint Barthélemy"});
			a.push({label:"Saint Helena", id:"Saint Helena"});
			a.push({label:"Saint Kitts and Nevis", id:"Saint Kitts and Nevis"});
			a.push({label:"Saint Lucia", id:"Saint Lucia"});
			a.push({label:"Saint Martin (French part)", id:"Saint Martin (French part)"});
			a.push({label:"Saint Pierre and Miquelon", id:"Saint Pierre and Miquelon"});
			a.push({label:"Saint Vincent and the Grenadines", id:"Saint Vincent and the Grenadines"});
			a.push({label:"Samoa", id:"Samoa"});
			a.push({label:"San Marino", id:"San Marino"});
			a.push({label:"Sao Tome and Principe", id:"Sao Tome and Principe"});
			a.push({label:"Saudi Arabia", id:"Saudi Arabia"});
			a.push({label:"Senegal", id:"Senegal"});
			a.push({label:"Serbia", id:"Serbia"});
			a.push({label:"Seychelles", id:"Seychelles"});
			a.push({label:"Sierra Leone", id:"Sierra Leone"});
			a.push({label:"Singapore", id:"Singapore"});
			a.push({label:"Slovakia", id:"Slovakia"});
			a.push({label:"Slovenia", id:"Slovenia"});
			a.push({label:"Solomon Islands", id:"Solomon Islands"});
			a.push({label:"Somalia", id:"Somalia"});
			a.push({label:"South Africa", id:"South Africa"});
			a.push({label:"South Georgia and the South Sandwich Islands", id:"South Georgia and the South Sandwich Islands"});
			a.push({label:"Spain", id:"Spain"});
			a.push({label:"Sri Lanka", id:"Sri Lanka"});
			a.push({label:"Sudan", id:"Sudan"});
			a.push({label:"Suriname", id:"Suriname"});
			a.push({label:"Svalbard and Jan Mayen", id:"Svalbard and Jan Mayen"});
			a.push({label:"Swaziland", id:"Swaziland"});
			a.push({label:"Sweden", id:"Sweden"});
			a.push({label:"Switzerland", id:"Switzerland"});
			a.push({label:"Syrian Arab Republic", id:"Syrian Arab Republic"});
			a.push({label:"Taiwan, Province of China", id:"Taiwan, Province of China"});
			a.push({label:"Tanzania, United Republic of", id:"Tanzania, United Republic of"});
			a.push({label:"Thailand", id:"Thailand"});
			a.push({label:"Timor-Leste", id:"Timor-Leste"});
			a.push({label:"Togo", id:"Togo"});
			a.push({label:"Tokelau", id:"Tokelau"});
			a.push({label:"Tonga", id:"Tonga"});
			a.push({label:"Trinidad and Tobago", id:"Trinidad and Tobago"});
			a.push({label:"Tunisia", id:"Tunisia"});
			a.push({label:"Turkey", id:"Turkey"});
			a.push({label:"Turkmenistan", id:"Turkmenistan"});
			a.push({label:"Turks and Caicos Islands", id:"Turks and Caicos Islands"});
			a.push({label:"Tuvalu", id:"Tuvalu"});
			a.push({label:"Ukraine", id:"Ukraine"});
			a.push({label:"United Arab Emirates", id:"United Arab Emirates"});
			a.push({label:"United Kingdom", id:"United Kingdom"});
			a.push({label:"United States", id:"United States"});
			a.push({label:"United States Minor Outlying Islands", id:"United States Minor Outlying Islands"});
			a.push({label:"Uruguay", id:"Uruguay"});
			a.push({label:"Uzbekistan", id:"Uzbekistan"});
			a.push({label:"Vanuatu", id:"Vanuatu"});
			a.push({label:"Venezuela", id:"Venezuela"});
			a.push({label:"Viet Nam", id:"Viet Nam"});
			a.push({label:"Virgin Islands, British", id:"Virgin Islands, British"});
			a.push({label:"Virgin Islands, U.S.", id:"Virgin Islands, U.S."});
			a.push({label:"Wallis and Futuna", id:"Wallis and Futuna"});
			a.push({label:"Yemen", id:"Yemen"});
			a.push({label:"Zambia", id:"Zambia"});
			a.push({label:"Zimbabwe", id:"Zimbabwe"});
			a.push({label:"Åland Islands", id:"Åland Islands"});
			return a;
		}
		
		
		public function CountriesArray()
		{
			
		}
	}
}

